/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vnngmghdwayxbgdgspag"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZubmdtZ2hkd2F5eGJnZGdzcGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjcxMDYsImV4cCI6MjA3Mzg0MzEwNn0.NC8VP2vz3SEnnJhH2CNttf-vPJXHaov022hH2gD0-QE"